apiVersion: v1
kind: Service
metadata:
  name: hello-world-nginx
  labels:
    app: hello-world-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: hello-world-nginx 